# wrangler.toml
name = "crypto-sync-awro"
main = "crypto_worker.js"
compatibility_date = "2025-10-08"

[vars]
SHOP_URL = "cb6c17-2.myshopify.com"
SHOP_TOKEN = "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"
CMC_API_KEY = "09c098c7-7631-4989-86f2-1d513f7dde28"
CMC_CONVERT = "USD"
