# wrangler.toml
name = "crypto-sync-awro"
main = "crypto_worker.js"
compatibility_date = "2025-10-08"

[vars]
SHOP_URL = "cb6c17-2.myshopify.com"
SHOP_TOKEN = "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"
CMC_API_KEY = "09c098c7-7631-4989-86f2-1d513f7dde28"
CMC_CONVERT = "EUR"
